version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - DATABASE_URL=postgresql://postgres:password@db:5432/bloom_store
            - JWT_SECRET=${JWT_SECRET:-your-secret-key}
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - bloom-network

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: bloom_store
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - bloom-network

volumes:
    postgres_data:

networks:
    bloom-network:
        driver: bridge
