version: '3.8'

services:
    app:
        build:
            dockerfile: Dockerfile
        container_name: bloom-app
        restart: unless-stopped
        env_file: '.env'
        environment:
            PORT: ${PORT}
        ports:
            - '${PORT}:3000'
        volumes:
            - bloom_app_data:/app
        networks:
            - bloom-network

volumes:
    bloom_app_data:
        driver: local

networks:
    bloom-network:
        external: true
