version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: bloom-store-db
        restart: unless-stopped
        env_file: '.env'
        environment:
            DATABASE_HOST: ${DB_HOST}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - '${DB_PORT}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - bloom-network

    # Опциональный pgAdmin для управления БД
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: bloom-store-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@bloom-store.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - bloom-network
        depends_on:
            - postgres

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local

networks:
    bloom-network:
        external: true
